## Outline
- **More on missing values**

In [ ]:
!gdown 173A59xh2mnpmljCCB9bhC4C5eP2IS6qZ

Downloading...
From: https://drive.google.com/uc?id=173A59xh2mnpmljCCB9bhC4C5eP2IS6qZ
To: /content/Pfizer_1.csv
100% 1.51k/1.51k [00:00<00:00, 2.48MB/s]

In [ ]:
import pandas as pd
import numpy as np
data = pd.read_csv('Pfizer_1.csv')

In [ ]:
data.head()

,Date,Drug_Name,Parameter,1:30:00,2:30:00,3:30:00,4:30:00,5:30:00,6:30:00,7:30:00,8:30:00,9:30:00,10:30:00,11:30:00,12:30:00
0,15-10-2020,diltiazem hydrochloride,Temperature,23.0,22.0,NaN,21.0,21.0,22,23.0,21.0,22.0,20,20.0,21
1,15-10-2020,diltiazem hydrochloride,Pressure,12.0,13.0,NaN,11.0,13.0,14,16.0,16.0,24.0,18,19.0,20
2,15-10-2020,docetaxel injection,Temperature,NaN,17.0,18.0,NaN,17.0,18,NaN,NaN,23.0,23,25.0,25
3,15-10-2020,docetaxel injection,Pressure,NaN,22.0,22.0,NaN,22.0,23,NaN,NaN,27.0,26,29.0,28
4,15-10-2020,ketamine hydrochloride,Temperature,24.0,NaN,NaN,27.0,NaN,26,25.0,24.0,23.0,22,21.0,20

## More on missing values

We have learnt how to fill values of one column using an estimator

#### Let's play around a bit more

We will look at two new methods, ```ffill``` and ```bfill```

In [ ]:
sample_df = data.head(10)
sample_df

,Date,Drug_Name,Parameter,1:30:00,2:30:00,3:30:00,4:30:00,5:30:00,6:30:00,7:30:00,8:30:00,9:30:00,10:30:00,11:30:00,12:30:00
0,15-10-2020,diltiazem hydrochloride,Temperature,23.0,22.0,NaN,21.0,21.0,22,23.0,21.0,22.0,20,20.0,21
1,15-10-2020,diltiazem hydrochloride,Pressure,12.0,13.0,NaN,11.0,13.0,14,16.0,16.0,24.0,18,19.0,20
2,15-10-2020,docetaxel injection,Temperature,NaN,17.0,18.0,NaN,17.0,18,NaN,NaN,23.0,23,25.0,25
3,15-10-2020,docetaxel injection,Pressure,NaN,22.0,22.0,NaN,22.0,23,NaN,NaN,27.0,26,29.0,28
4,15-10-2020,ketamine hydrochloride,Temperature,24.0,NaN,NaN,27.0,NaN,26,25.0,24.0,23.0,22,21.0,20
5,15-10-2020,ketamine hydrochloride,Pressure,8.0,NaN,NaN,7.0,NaN,9,10.0,11.0,10.0,9,9.0,11
6,16-10-2020,diltiazem hydrochloride,Temperature,34.0,35.0,36.0,36.0,37.0,38,37.0,38.0,39.0,40,NaN,42
7,16-10-2020,diltiazem hydrochloride,Pressure,18.0,19.0,20.0,21.0,22.0,23,24.0,25.0,25.0,24,NaN,27
8,16-10-2020,docetaxel injection,Temperature,46.0,47.0,NaN,48.0,48.0,49,50.0,52.0,55.0,56,57.0,58
9,16-10-2020,docetaxel injection,Pressure,23.0,24.0,NaN,25.0,26.0,27,28.0,29.0,28.0,28,29.0,30

In [ ]:
sample_df.fillna(method='ffill')

,Date,Drug_Name,Parameter,1:30:00,2:30:00,3:30:00,4:30:00,5:30:00,6:30:00,7:30:00,8:30:00,9:30:00,10:30:00,11:30:00,12:30:00
0,15-10-2020,diltiazem hydrochloride,Temperature,23.0,22.0,NaN,21.0,21.0,22,23.0,21.0,22.0,20,20.0,21
1,15-10-2020,diltiazem hydrochloride,Pressure,12.0,13.0,NaN,11.0,13.0,14,16.0,16.0,24.0,18,19.0,20
2,15-10-2020,docetaxel injection,Temperature,12.0,17.0,18.0,11.0,17.0,18,16.0,16.0,23.0,23,25.0,25
3,15-10-2020,docetaxel injection,Pressure,12.0,22.0,22.0,11.0,22.0,23,16.0,16.0,27.0,26,29.0,28
4,15-10-2020,ketamine hydrochloride,Temperature,24.0,22.0,22.0,27.0,22.0,26,25.0,24.0,23.0,22,21.0,20
5,15-10-2020,ketamine hydrochloride,Pressure,8.0,22.0,22.0,7.0,22.0,9,10.0,11.0,10.0,9,9.0,11
6,16-10-2020,diltiazem hydrochloride,Temperature,34.0,35.0,36.0,36.0,37.0,38,37.0,38.0,39.0,40,9.0,42
7,16-10-2020,diltiazem hydrochloride,Pressure,18.0,19.0,20.0,21.0,22.0,23,24.0,25.0,25.0,24,9.0,27
8,16-10-2020,docetaxel injection,Temperature,46.0,47.0,20.0,48.0,48.0,49,50.0,52.0,55.0,56,57.0,58
9,16-10-2020,docetaxel injection,Pressure,23.0,24.0,20.0,25.0,26.0,27,28.0,29.0,28.0,28,29.0,30

#### What do we notice here?

Forward fill basically replaces the null value with the value just before it.

Thus, at row 2, the NaN value of `1:30:00` column gets replaced by 12 value of row 1

In [ ]:
sample_df.fillna(method='bfill')

,Date,Drug_Name,Parameter,1:30:00,2:30:00,3:30:00,4:30:00,5:30:00,6:30:00,7:30:00,8:30:00,9:30:00,10:30:00,11:30:00,12:30:00
0,15-10-2020,diltiazem hydrochloride,Temperature,23.0,22.0,18.0,21.0,21.0,22,23.0,21.0,22.0,20,20.0,21
1,15-10-2020,diltiazem hydrochloride,Pressure,12.0,13.0,18.0,11.0,13.0,14,16.0,16.0,24.0,18,19.0,20
2,15-10-2020,docetaxel injection,Temperature,24.0,17.0,18.0,27.0,17.0,18,25.0,24.0,23.0,23,25.0,25
3,15-10-2020,docetaxel injection,Pressure,24.0,22.0,22.0,27.0,22.0,23,25.0,24.0,27.0,26,29.0,28
4,15-10-2020,ketamine hydrochloride,Temperature,24.0,35.0,36.0,27.0,37.0,26,25.0,24.0,23.0,22,21.0,20
5,15-10-2020,ketamine hydrochloride,Pressure,8.0,35.0,36.0,7.0,37.0,9,10.0,11.0,10.0,9,9.0,11
6,16-10-2020,diltiazem hydrochloride,Temperature,34.0,35.0,36.0,36.0,37.0,38,37.0,38.0,39.0,40,57.0,42
7,16-10-2020,diltiazem hydrochloride,Pressure,18.0,19.0,20.0,21.0,22.0,23,24.0,25.0,25.0,24,57.0,27
8,16-10-2020,docetaxel injection,Temperature,46.0,47.0,NaN,48.0,48.0,49,50.0,52.0,55.0,56,57.0,58
9,16-10-2020,docetaxel injection,Pressure,23.0,24.0,NaN,25.0,26.0,27,28.0,29.0,28.0,28,29.0,30

#### Now what did bfill do exactly?

Opposite to forward fill, it replaced the NaN values with the values after them.

This replacement works upwards, while forward fill works downward.

#### Now let's look at another interesting concept, the change of dtype by fillna

In [ ]:
sample_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 15 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       10 non-null     object
 1   Drug_Name  10 non-null     object
 2   Parameter  10 non-null     object
 3   1:30:00    8 non-null      float64
 4   2:30:00    8 non-null      float64
 5   3:30:00    4 non-null      float64
 6   4:30:00    8 non-null      float64
 7   5:30:00    8 non-null      float64
 8   6:30:00    10 non-null     int64
 9   7:30:00    8 non-null      float64
 10  8:30:00    8 non-null      float64
 11  9:30:00    10 non-null     float64
 12  10:30:00   10 non-null     int64
 13  11:30:00   8 non-null      float64
 14  12:30:00   10 non-null     int64
dtypes: float64(9), int64(3), object(3)
memory usage: 1.3+ KB

As we can see, the dtype of `1:30:00` column is float64

Now what happens if we use fillna on this?

In [ ]:
sample_df.fillna(0).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 15 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       10 non-null     object
 1   Drug_Name  10 non-null     object
 2   Parameter  10 non-null     object
 3   1:30:00    10 non-null     float64
 4   2:30:00    10 non-null     float64
 5   3:30:00    10 non-null     float64
 6   4:30:00    10 non-null     float64
 7   5:30:00    10 non-null     float64
 8   6:30:00    10 non-null     int64
 9   7:30:00    10 non-null     float64
 10  8:30:00    10 non-null     float64
 11  9:30:00    10 non-null     float64
 12  10:30:00   10 non-null     int64
 13  11:30:00   10 non-null     float64
 14  12:30:00   10 non-null     int64
dtypes: float64(9), int64(3), object(3)
memory usage: 1.3+ KB

It's the same, but now, what if we use a string in fillna?

In [ ]:
sample_df.fillna("Couldn't Take Reading").info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 15 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       10 non-null     object
 1   Drug_Name  10 non-null     object
 2   Parameter  10 non-null     object
 3   1:30:00    10 non-null     object
 4   2:30:00    10 non-null     object
 5   3:30:00    10 non-null     object
 6   4:30:00    10 non-null     object
 7   5:30:00    10 non-null     object
 8   6:30:00    10 non-null     int64
 9   7:30:00    10 non-null     object
 10  8:30:00    10 non-null     object
 11  9:30:00    10 non-null     float64
 12  10:30:00   10 non-null     int64
 13  11:30:00   10 non-null     object
 14  12:30:00   10 non-null     int64
dtypes: float64(1), int64(3), object(11)
memory usage: 1.3+ KB

#### When we replace the value with string, it changes the dtype of object.

Remember from our earlier discussions, a string based column is considered an object dtype

This is what exactly happened here.